name: Run Selected GTest Cases

on:
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use Linux as the environment

    steps:
        - name: Checkout code
          uses: actions/checkout@v4
            
        - name: Send Diff to Backend
          run: |
            curl -X POST "https://28d9-197-133-69-11.ngrok-free.app/codebase/analyze?repo_name=${{ github.repository }}" \
                -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0MTU2ODA2MSwianRpIjoiYThmZTZhYWUtZDMzYi00MGI5LWI3NGMtYWE2MTBkNjE4OGFiIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MywibmJmIjoxNzQxNTY4MDYxLCJjc3JmIjoiMjE1ZDczNTItZjk3MS00YTIxLThkNzAtNjk4NDZkYWUxNjdkIiwiZXhwIjoxNzQxNTY4OTYxfQ.y7RC7TkUtgnkBL6FyLAzdPP0-wqRKL1VbiWYZAQu4Q8" \
                -H "Content-Type: application/json" \
                -d '{
                }'
