name: Run GTest Tests

on:
  workflow_dispatch:
    inputs:
      test_names:
        description: 'JSON array of test names to run'
        required: true
        default: '[]'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libgtest-dev jq
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp lib/*.a /usr/lib || sudo cp /usr/src/gtest/lib/*.a /usr/lib

      - name: Debug environment
        run: |
          ls -la
          ls -l /usr/lib/libgtest*
          ls -l /usr/include/gtest

      - name: Compile with Clang
        run: |
          clang++ -std=c++14 -I/usr/include/gtest -L/usr/lib -lgtest -lgtest_main -pthread *.cpp -o test_executable -v
        shell: bash

      - name: Run specific tests
        run: |
          TEST_FILTER=$(echo '${{ github.event.inputs.test_names }}' | jq -r 'join(":")')
          if [ -z "$TEST_FILTER" ] || [ "$TEST_FILTER" = "[]" ]; then
            echo "No specific tests provided, running all tests"
            ./test_executable
          else
            echo "Running tests: $TEST_FILTER"
            ./test_executable --gtest_filter="$TEST_FILTER"
          fi
        shell: bash
