name: Run GTest Tests

on:
  workflow_dispatch:
    inputs:
      test_names:
        description: 'JSON array of test names to run'
        required: true
        default: '[]'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libgtest-dev jq
          cd /usr/src/googletest
          sudo mkdir -p build
          cd build
          sudo cmake ..
          sudo make
          sudo cp lib/*.a /usr/lib

      - name: Debug environment
        run: |
          ls -la
          ls -l /usr/lib/libgtest* || echo "GTest libraries not found in /usr/lib"
          ls -l /usr/include/gtest || echo "GTest headers not found"

      - name: Compile with Clang
        run: |
          clang++ -std=c++14 -I/usr/include/gtest *.cpp -L/usr/lib -lgtest -lgtest_main -pthread -o test_executable -v
        shell: bash

      - name: Run specific tests
        run: |
          TEST_FILTER=$(echo '${{ github.event.inputs.test_names }}' | jq -r 'join(":")')
          if [ -z "$TEST_FILTER" ] || [ "$TEST_FILTER" = "[]" ]; then
            echo "No specific tests provided, running all tests"
            ./test_executable
          else
            echo "Running tests: $TEST_FILTER"
            ./test_executable --gtest_filter="$TEST_FILTER"
          fi
        shell: bash
